name: eps-docs
url: http://localhost:8111
path: /
static-path: doku/static
pygments:
  style: tango
  class: codehilite
languages:
  #these pages will be copied to all languages
  $all:
    pages:
      - src: common/404.html
        hidden: true
        footer: false
        attrs:
          sitemap: false
        title: 404
        slug: '404'
        name: '404'
translations:
  hp:
    site-title:
      _t:
        de: d7148d9fd0cd368b
        en: d7148d9fd0cd368b
      de: EPS-Dokumentation
      en: EPS documentation
#translations:
#  $include: translations/index.yml
context:
  env: development
